---
module_name: hashset
version: 0.1.0
hash: a01e95d86babff9ecbd583f733f2685d
module_paths:
  - "${MODULES_PATH}"
modules:
  hash:
    path: "${MODULES_PATH}/prelude/hash"
    version: 0.1.0
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
  range:
    path: "${MODULES_PATH}/prelude/range"
    version: 0.1.0
