---
module_name: hashmap
version: 0.1.0
hash: 44fdcb9f6f8e89db43935fa805422222
module_paths:
  - "${MODULES_PATH}"
modules:
  hash:
    path: "${MODULES_PATH}/prelude/hash"
    version: 0.1.0
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
  range:
    path: "${MODULES_PATH}/prelude/range"
    version: 0.1.0
