---
module_name: hashmap
version: 0.1.0
hash: 330eb8f8b98dfef2554a10d13f5b56a9
module_paths:
  - "${MODULES_PATH}"
modules:
  range:
    path: "${MODULES_PATH}/prelude/range"
    version: 0.1.0
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
  hash:
    path: "${MODULES_PATH}/prelude/hash"
    version: 0.1.0
