---
module_name: array_extensions
version: 0.1.0
hash: ec5a9f79c90fd17845d6bf669dbf4b40
module_paths:
  - "${MODULES_PATH}"
modules:
  range:
    path: "${MODULES_PATH}/prelude/range"
    version: 0.1.0
