---
module_name: string_extensions
version: 0.1.0
hash: 094440cfab75427ff673c7d1650992a6
module_paths:
  - "${MODULES_PATH}"
modules:
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
