---
module_name: string_extensions
version: 0.1.0
hash: ebed96914462f51f7761f7c0727e86c7
module_paths:
  - "${MODULES_PATH}"
modules:
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
