---
module_name: string_extensions
version: 0.1.0
hash: 640cb7c5d60cd3078965585238389a4a
module_paths:
  - "${MODULES_PATH}"
modules:
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
